apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-go
  template:
    metadata:
      labels:
        app: todo-go
    spec:
      containers:
        - name: todo-go
          image: djblackett/todo-go:v0.3.2
          env:
            - name: PORT
              value: "8000"
