apiVersion: v1
kind: Service
metadata:
  namespace: development
  name: log-output-lb
spec:
  type: LoadBalancer
  selector:
    app: log-output
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080