apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/backend.deployment.yaml
  - manifests/frontend.deployment.yaml
  - manifests/ingress.yaml
  - manifests/job.yaml
  - manifests/postgres-init-config.yaml
  - manifests/postgres-statefulset.yaml
  - manifests/web-configmap.yaml
  - manifests/backup.yaml
  - volumes/persistantvolume.yaml
  - volumes/persistentvolumeclaim.yaml
