apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-rando
  labels:
    app: wiki-rando
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki-rando
  template:
    metadata:
      labels:
        app: wiki-rando
    spec:
      initContainers:
      - name: website-downloader
        image: alpine:3.16
        command: ["sh", "-c", "mkdir -p /mnt/website && wget -O /mnt/website/index.html https://en.wikipedia.org/wiki/Kubernetes "]
        volumeMounts:
        - mountPath: /mnt/website
          name: website-volume
        resources:
          requests:
            cpu: "50m"
            memory: "50Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
      containers:
      - name: nginx-server
        image: nginx:1.27.0-alpine
        ports:
        - containerPort: 80

        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: website-volume

        resources:
          requests:
            cpu: "50m"
            memory: "50Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"

      - name: randomizer
        image: alpine:3.16
        command: ["sh", "/scripts/download-website.sh"]
        volumeMounts:
        - mountPath: /mnt/website
          name: website-volume
        - name: script-volume
          mountPath: /scripts/download-website.sh
          subPath: download-website.sh
          readOnly: true

        resources:
          requests:
            cpu: "50m"
            memory: "50Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"


      volumes:
      - name: website-volume
        emptyDir: {}
      - name: script-volume
        configMap:
          name: script-configmap
          items:
          - key: download-website.sh
            path: download-website.sh



---

apiVersion: v1
kind: Service
metadata:
  name: wiki-rando-svc
spec:
  type: ClusterIP
  selector:
    app: wiki-rando
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wiki-rando-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wiki-rando-svc
            port:
              number: 80
