apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: development
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output
          image: djblackett/log-output:v2.01.2
          env:
            - name: PING_PONG_SERVICE
              value: "http://ping-pong-svc:2345"
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  namespace: development
  name: log-output-svc
spec:
  type: ClusterIP
  selector:
    app: log-output
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 8080