apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-image
          emptyDir: {}
      containers:
        - name: log-output
          image: djblackett/log-printer:v0.4
          volumeMounts: # Mount volume
            - name: shared-image
              mountPath: /files
        - name: timestamp
          image: djblackett/timestamp-writer:v0.3
          volumeMounts: # Mount volume
            - name: shared-image
              mountPath: /files
