apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-provider
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/x-circle-428403-n6/secrets/postgres-password/versions/SECRET_VERSION"
        path: "FILENAME.txt"

# experimenting with various methods of managing secrets. This is not currently in use.
